name: uidb
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  get: ^4.6.5
  intl_phone_field: ^3.1.0
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  flutter_otp_text_field: ^1.1.0+2
  cloud_firestore: ^4.4.4
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/welcome_images/
    - assets/images/splash_images/
    - assets/images/forgot_password_images/
    - assets/images/profile_images/

  
